# Generated by Django 3.2.3 on 2021-06-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
